# Библиотека NumPy

Выполняйте задания прямо в этом блокноте. При необходимости, можете создавать новые ячейки для кода или текста.

# После этой ячейки обязательно сделайте ещё одну Markdown ячейку, в которой напишите своё ФИО и номер группы, а также соответствующим образом назовите файл!

## Задание 1: Изучение массивов NumPy

### 1. Создание массива и его свойства.
Создайте одномерный массив NumPy из списка Python и двумерный массив из списка списков.
Выведите форму, размер и тип данных этих массивов.

In [4]:
import numpy as np

list_1d = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
array_1d = np.array(list_1d)


print("\n" + "="*50 + "\n")

print("Одномерный массив")
print("Исходный список:", list_1d)
print("Массив NumPy:", array_1d)
print("Форма (shape):", array_1d.shape)
print("Размер (size):", array_1d.size)
print("Тип данных (dtype):", array_1d.dtype)

print("\n" + "="*50 + "\n")

list_2d = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
array_2d = np.array(list_2d)

print("Двумерный массив")
print("Исходный список списков:")
for row in list_2d:
    print(row)
print("\nМассив NumPy:")
print(array_2d)
print("\nФорма (shape):", array_2d.shape)
print("Размер (size):", array_2d.size)
print("Тип данных (dtype):", array_2d.dtype)

print("\n" + "="*50 + "\n")



Одномерный массив
Исходный список: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Массив NumPy: [ 1  2  3  4  5  6  7  8  9 10]
Форма (shape): (10,)
Размер (size): 10
Тип данных (dtype): int64


Двумерный массив
Исходный список списков:
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]

Массив NumPy:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Форма (shape): (3, 4)
Размер (size): 12
Тип данных (dtype): int64




### 2. Индексирование и разрезание массивов.
Получите доступа к определенным элементам, строкам и столбцам двумерного массива.
Создайте подмассив с помощью среза и измените его элемент.

In [10]:
import numpy as np

list_1d = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
array_1d = np.array(list_1d)
print("\n" + "="*50 + "\n")
print("Одномерный массив")
print("Исходный список:", list_1d)
print("Массив NumPy:", array_1d)
print("Форма (shape):", array_1d.shape)
print("Размер (size):", array_1d.size)
print("Тип данных (dtype):", array_1d.dtype)
print("\n" + "="*50 + "\n")

list_2d = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
array_2d = np.array(list_2d)
print("Двумерный массив")
print("Исходный список списков:")
for row in list_2d:
    print(row)
print("\nМассив NumPy:")
print(array_2d)
print("\nФорма (shape):", array_2d.shape)
print("Размер (size):", array_2d.size)
print("Тип данных (dtype):", array_2d.dtype)
print("\n" + "="*50 + "\n")

print("Доступ к элементам:")
print("array_2d[0, 0] =", array_2d[0, 0])
print("array_2d[1, 2] =", array_2d[1, 2])
print("array_2d[2, 3] =", array_2d[2, 3])
print("\n" + "="*50 + "\n")

print("Доступ к строкам:")
print("array_2d[0] =", array_2d[0])
print("array_2d[1] =", array_2d[1])
print("array_2d[2] =", array_2d[2])
print("\n" + "="*50 + "\n")

print("Доступ к столбцам:")
print("array_2d[:, 0] =", array_2d[:, 0])
print("array_2d[:, 1] =", array_2d[:, 1])
print("array_2d[:, 2] =", array_2d[:, 2])
print("array_2d[:, 3] =", array_2d[:, 3])
print("\n" + "="*50 + "\n")

print("Срезы:")
print("array_2d 0:2, 1:3] =")
subarray = array_2d[0:2, 1:3]
print(subarray)
print("\n" + "="*50 + "\n")

print("Изменение подмассива:")
print("До: subarray[0, 0] =", subarray[0, 0])
subarray[0, 0] = 999
print("После: subarray[0, 0] =", subarray[0, 0])
print("\nИсходный массив:")
print(array_2d)
print("\n" + "="*50 + "\n")



Одномерный массив
Исходный список: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Массив NumPy: [ 1  2  3  4  5  6  7  8  9 10]
Форма (shape): (10,)
Размер (size): 10
Тип данных (dtype): int64


Двумерный массив
Исходный список списков:
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]

Массив NumPy:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Форма (shape): (3, 4)
Размер (size): 12
Тип данных (dtype): int64


Доступ к элементам:
array_2d[0, 0] = 1
array_2d[1, 2] = 7
array_2d[2, 3] = 12


Доступ к строкам:
array_2d[0] = [1 2 3 4]
array_2d[1] = [5 6 7 8]
array_2d[2] = [ 9 10 11 12]


Доступ к столбцам:
array_2d[:, 0] = [1 5 9]
array_2d[:, 1] = [ 2  6 10]
array_2d[:, 2] = [ 3  7 11]
array_2d[:, 3] = [ 4  8 12]


Срезы:
array_2d 0:2, 1:3] =
[[2 3]
 [6 7]]


Изменение подмассива:
До: subarray[0, 0] = 2
После: subarray[0, 0] = 999

Исходный массив:
[[  1 999   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]




### 3. Операции с массивами.
Выполните поэлементное сложение, вычитание, умножение и деление в массивах

In [11]:
import numpy as np

array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([1, 2, 3, 4, 5])

print("\n" + "="*50 + "\n")
print("Массив 1:", array1)
print("Массив 2:", array2)
print("\n" + "="*50 + "\n")

print("Сложение:")
print(array1 + array2)
print("\n" + "="*50 + "\n")

print("Вычитание:")
print(array1 - array2)
print("\n" + "="*50 + "\n")

print("Умножение:")
print(array1 * array2)
print("\n" + "="*50 + "\n")

print("Деление:")
print(array1 / array2)
print("\n" + "="*50 + "\n")

array_2d_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2d_2 = np.array([[10, 20, 30], [40, 50, 60]])

print("Двумерные массивы:")
print("Массив 1:")
print(array_2d_1)
print("Массив 2:")
print(array_2d_2)
print("\n" + "="*50 + "\n")

print("Сложение 2D:")
print(array_2d_1 + array_2d_2)
print("\n" + "="*50 + "\n")

print("Вычитание 2D:")
print(array_2d_1 - array_2d_2)
print("\n" + "="*50 + "\n")

print("Умножение 2D:")
print(array_2d_1 * array_2d_2)
print("\n" + "="*50 + "\n")

print("Деление 2D:")
print(array_2d_1 / array_2d_2)
print("\n" + "="*50 + "\n")



Массив 1: [10 20 30 40 50]
Массив 2: [1 2 3 4 5]


Сложение:
[11 22 33 44 55]


Вычитание:
[ 9 18 27 36 45]


Умножение:
[ 10  40  90 160 250]


Деление:
[10. 10. 10. 10. 10.]


Двумерные массивы:
Массив 1:
[[1 2 3]
 [4 5 6]]
Массив 2:
[[10 20 30]
 [40 50 60]]


Сложение 2D:
[[11 22 33]
 [44 55 66]]


Вычитание 2D:
[[ -9 -18 -27]
 [-36 -45 -54]]


Умножение 2D:
[[ 10  40  90]
 [160 250 360]]


Деление 2D:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]




### 4. Переформирование и конкатенация.
Перестройте двумерный массив в другую форму (например, из 4x3 в 3x4).

In [13]:
import numpy as np

array_original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print("\n" + "="*50 + "\n")
print("Исходный массив 4x3:")
print(array_original)
print("Форма:", array_original.shape)
print("\n" + "="*50 + "\n")

array_reshaped = array_original.reshape(3, 4)
print("Массив 3x4:")
print(array_reshaped)
print("Форма:", array_reshaped.shape)
print("\n" + "="*50 + "\n")

array_reshaped_2x6 = array_original.reshape(2, 6)
print("Массив 2x6:")
print(array_reshaped_2x6)
print("Форма:", array_reshaped_2x6.shape)
print("\n" + "="*50 + "\n")




Исходный массив 4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Форма: (4, 3)


Массив 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма: (3, 4)


Массив 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Форма: (2, 6)




## Задание 2: Случайные числа и статистический анализ

### 1. Генерация случайных чисел.
Сгенерируйте одномерный массив из 100 случайных чисел с помощью NumPy `random.rand`.
Создайте двумерный массив случайных целых чисел заданной формы с помощью NumPy [`random.randint`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html).

In [17]:
import numpy as np

print("\n" + "="*50 + "\n")
print("Одномерный массив из 100 рандоных чисел:")
array_rand = np.random.rand(100)
print(array_rand)
print("Форма:", array_rand.shape)
print("Размер:", array_rand.size)
print("\n" + "="*50 + "\n")

print("Двумерный массив 3x4 рандомных числе(от 1 до 10):")
array_randint_small = np.random.randint(1, 11, size=(3, 4))
print(array_randint_small)
print("Форма:", array_randint_small.shape)
print("\n" + "="*50 + "\n")



Одномерный массив из 100 рандоных чисел:
[0.58419508 0.13012256 0.87973242 0.73809466 0.52752456 0.21753881
 0.28952365 0.56735084 0.59584449 0.38540487 0.012117   0.59410144
 0.944402   0.61606216 0.89478802 0.87103248 0.56677573 0.44390335
 0.51293319 0.75556283 0.91491403 0.20624647 0.81021675 0.55896163
 0.11975437 0.73755834 0.10948387 0.36612643 0.6699155  0.73560985
 0.93806209 0.90392008 0.82008191 0.55075707 0.69887125 0.48148431
 0.73283509 0.73084306 0.99971026 0.61517886 0.80128172 0.66049884
 0.17019028 0.36969432 0.76655414 0.49886575 0.80486376 0.53912644
 0.01717106 0.61693036 0.3473507  0.6821747  0.54423917 0.50116722
 0.33966021 0.28262455 0.62040302 0.66676381 0.43204647 0.13340297
 0.11889103 0.93791557 0.15435794 0.84158971 0.97379516 0.30771613
 0.89206847 0.28063411 0.60232274 0.5946881  0.51233307 0.92605641
 0.78355599 0.50017802 0.44381741 0.16103461 0.85650618 0.50193873
 0.34731512 0.0920012  0.51207218 0.43539733 0.32151356 0.92477807
 0.09953936 0.80041

### 2. Статистический анализ.
Вычислите и выведите среднее значение, медиану и стандартное отклонение сгенерированных массивов.
Найдите минимальное и максимальное значения в массивах.

In [18]:
import numpy as np

array_rand = np.random.rand(100)
array_randint = np.random.randint(0, 101, size=(5, 7))

print("\n" + "="*50 + "\n")
print("Массив из 100 случайных чисел:")
print("Среднее:", array_rand.mean())
print("Медиана:", np.median(array_rand))
print("Стандартное отклонение:", array_rand.std())
print("Минимум:", array_rand.min())
print("Максимум:", array_rand.max())
print("\n" + "="*50 + "\n")

print("Массив 5x8 случайных целых чисел:")
print(array_randint)
print("\nСреднее:", array_randint.mean())
print("Медиана:", np.median(array_randint))
print("Стандартное отклонение:", array_randint.std())
print("Минимум:", array_randint.min())
print("Максимум:", array_randint.max())
print("\n" + "="*50 + "\n")

print("Статистика по строкам:")
print("Среднее по строкам:", array_randint.mean(axis=1))
print("Минимум по строкам:", array_randint.min(axis=1))
print("Максимум по строкам:", array_randint.max(axis=1))
print("\n" + "="*50 + "\n")

print("Статистика по столбцам:")
print("Среднее по столбцам:", array_randint.mean(axis=0))
print("Минимум по столбцам:", array_randint.min(axis=0))
print("Максимум по столбцам:", array_randint.max(axis=0))
print("\n" + "="*50 + "\n")



Массив из 100 случайных чисел:
Среднее: 0.480294111645713
Медиана: 0.48547359326634565
Стандартное отклонение: 0.2835924038511187
Минимум: 0.005188460729458777
Максимум: 0.9930150050496034


Массив 5x8 случайных целых чисел:
[[ 6 81 43 36 54 83 89]
 [58  0 86 86 54 52 82]
 [ 1 94 89 30 53 47 86]
 [ 0 43 82 36 37 69  8]
 [11 45 31 46 51 75 84]]

Среднее: 52.22857142857143
Медиана: 52.0
Стандартное отклонение: 28.851428005545642
Минимум: 0
Максимум: 94


Статистика по строкам:
Среднее по строкам: [56.         59.71428571 57.14285714 39.28571429 49.        ]
Минимум по строкам: [ 6  0  1  0 11]
Максимум по строкам: [89 86 94 82 84]


Статистика по столбцам:
Среднее по столбцам: [15.2 52.6 66.2 46.8 49.8 65.2 69.8]
Минимум по столбцам: [ 0  0 31 30 37 47  8]
Максимум по столбцам: [58 94 89 86 54 83 89]




## Задание 3: Продвинутые операции с массивами NumPy

### 1. Матричные операции.
Создайте две матрицы заданной размерности.
Выполняйте сложение, вычитание и умножение матриц.

In [19]:
import numpy as np

matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("\n" + "="*50 + "\n")
print("Матрица 1:")
print(matrix1)
print("\nМатрица 2:")
print(matrix2)
print("\n" + "="*50 + "\n")

print("Сложение матриц:")
print(matrix1 + matrix2)
print("\n" + "="*50 + "\n")

print("Вычитание матриц:")
print(matrix1 - matrix2)
print("\n" + "="*50 + "\n")

print("Поэлементное умножение:")
print(matrix1 * matrix2)
print("\n" + "="*50 + "\n")

print("Матричное умножение:")
print(np.dot(matrix1, matrix2))
print("\n" + "="*50 + "\n")



Матрица 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


Сложение матриц:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


Вычитание матриц:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


Поэлементное умножение:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Матричное умножение:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]




Создайте два или более массивов и выполните операции соединения (горизонтальное и вертикальное) с помощью указания параметра `axis` у метода `concatenate`. Измените форму одного из массивов с помощью `reshape`.

In [20]:
import numpy as np

matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("\n" + "="*50 + "\n")
print("Матрица 1:")
print(matrix1)
print("\nМатрица 2:")
print(matrix2)
print("\n" + "="*50 + "\n")

print("Вертикальное соединение (axis=0):")
vertical = np.concatenate((matrix1, matrix2), axis=0)
print(vertical)
print("Форма:", vertical.shape)
print("\n" + "="*50 + "\n")

print("Горизонтальное соединение (axis=1):")
horizontal = np.concatenate((matrix1, matrix2), axis=1)
print(horizontal)
print("Форма:", horizontal.shape)
print("\n" + "="*50 + "\n")

print("Reshape matrix1 1x9:")
reshaped1 = matrix1.reshape(1, 9)
print(reshaped1)
print("Форма:", reshaped1.shape)
print("\n" + "="*50 + "\n")




Матрица 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


Вертикальное соединение (axis=0):
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
Форма: (6, 3)


Горизонтальное соединение (axis=1):
[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]
Форма: (3, 6)


Reshape matrix1 1x9:
[[1 2 3 4 5 6 7 8 9]]
Форма: (1, 9)




### 2. Булевы операции.
Примените булевы операции к массиву.

In [26]:
import numpy as np

matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("\n" + "="*50 + "\n")
print("Матрица 1:")
print(matrix1)
print("\n" + "="*50 + "\n")

print(">5:")
print(matrix1 > 5)
print("\n" + "="*50 + "\n")

print("<=5:")
print(matrix1 <= 5)
print("\n" + "="*50 + "\n")

print("==5:")
print(matrix1 == 5)
print("\n" + "="*50 + "\n")

print("Чет:")
print(matrix1[matrix1 % 2 == 0])
print("\n" + "="*50 + "\n")

print("Нечет:")
print(matrix1[matrix1 % 2 != 0])
print("\n" + "="*50 + "\n")



Матрица 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


>5:
[[False False False]
 [False False  True]
 [ True  True  True]]


<=5:
[[ True  True  True]
 [ True  True False]
 [False False False]]


==5:
[[False False False]
 [False  True False]
 [False False False]]


Чет:
[2 4 6 8]


Нечет:
[1 3 5 7 9]


