# Практическая работа №1
## Тема: использование библиотеки NumPy

**ФИО:Повх Иван Олегович**  
**Номер группы: 2-ИСИП-724**

### Задание 2: Импорт библиотеки NumPy

In [1]:
import numpy as np
print("NumPy версия:", np.__version__)

NumPy версия: 1.26.4


### Задание 3: Создание массивов разных размерностей

In [2]:
# Одномерный массив
array_1d = np.array([1, 2, 3, 4, 5])
print("Одномерный массив:")
print(array_1d)
print()

# Двухмерный массив
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Двухмерный массив:")
print(array_2d)
print()

# Трёхмерный массив
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Трёхмерный массив:")
print(array_3d)

Одномерный массив:
[1 2 3 4 5]

Двухмерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Трёхмерный массив:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Задание 4: Изучение основных свойств массивов

In [3]:
# Свойства одномерного массива
print("Одномерный массив")
print(f"Количество измерений (ndim): {array_1d.ndim}")
print(f"Размерность (shape): {array_1d.shape}")
print(f"Тип данных (dtype): {array_1d.dtype}")
print(f"Количество элементов (size): {array_1d.size}")
print()

# Свойства двухмерного массива
print("Двухмерный массив")
print(f"Количество измерений (ndim): {array_2d.ndim}")
print(f"Размерность (shape): {array_2d.shape}")
print(f"Тип данных (dtype): {array_2d.dtype}")
print(f"Количество элементов (size): {array_2d.size}")
print()

# Свойства трёхмерного массива
print("Трёхмерный массив")
print(f"Количество измерений (ndim): {array_3d.ndim}")
print(f"Размерность (shape): {array_3d.shape}")
print(f"Тип данных (dtype): {array_3d.dtype}")
print(f"Количество элементов (size): {array_3d.size}")

Одномерный массив
Количество измерений (ndim): 1
Размерность (shape): (5,)
Тип данных (dtype): int64
Количество элементов (size): 5

Двухмерный массив
Количество измерений (ndim): 2
Размерность (shape): (3, 3)
Тип данных (dtype): int64
Количество элементов (size): 9

Трёхмерный массив
Количество измерений (ndim): 3
Размерность (shape): (2, 2, 2)
Тип данных (dtype): int64
Количество элементов (size): 8


### Задание 5: Математические операции массивов с числами

In [4]:
# Операции с одномерным массивом
print("Одномерный массив")
print("Исходный массив:", array_1d)
print("Сложение с 10:", array_1d + 10)
print("Вычитание 3:", array_1d - 3)
print("Умножение на 2:", array_1d * 2)
print("Деление на 2:", array_1d / 2)
print()

# Операции с двухмерным массивом
print("Двухмерный массив")
print("Исходный массив:")
print(array_2d)
print("Сложение с 5:")
print(array_2d + 5)
print("Вычитание 2:")
print(array_2d - 2)
print("Умножение на 3:")
print(array_2d * 3)
print("Деление на 3:")
print(array_2d / 3)
print()

# Операции с трёхмерным массивом
print("Трёхмерный массив")
print("Исходный массив:")
print(array_3d)
print("Сложение с 100:")
print(array_3d + 100)
print("Вычитание 1:")
print(array_3d - 1)
print("Умножение на 5:")
print(array_3d * 5)
print("Деление на 2:")
print(array_3d / 2)

Одномерный массив
Исходный массив: [1 2 3 4 5]
Сложение с 10: [11 12 13 14 15]
Вычитание 3: [-2 -1  0  1  2]
Умножение на 2: [ 2  4  6  8 10]
Деление на 2: [0.5 1.  1.5 2.  2.5]

Двухмерный массив
Исходный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Сложение с 5:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Вычитание 2:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
Умножение на 3:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
Деление на 3:
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]

Трёхмерный массив
Исходный массив:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Сложение с 100:
[[[101 102]
  [103 104]]

 [[105 106]
  [107 108]]]
Вычитание 1:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Умножение на 5:
[[[ 5 10]
  [15 20]]

 [[25 30]
  [35 40]]]
Деление на 2:
[[[0.5 1. ]
  [1.5 2. ]]

 [[2.5 3. ]
  [3.5 4. ]]]


### Задание 6: Математические операции между массивами

In [5]:
# Создание копии двухмерного массива
array_2d_copy = array_2d.copy()
print("Копия двухмерного массива:")
print(array_2d_copy)
print()

# Создание нового двухмерного массива
array_2d_new = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Новый двухмерный массив:")
print(array_2d_new)
print()

# Математические операции между массивами
print("Сложение массивов:")
print(array_2d_copy + array_2d_new)
print()

print("Вычитание массивов:")
print(array_2d_copy - array_2d_new)
print()

print("Умножение массивов (поэлементное):")
print(array_2d_copy * array_2d_new)
print()

print("Деление массивов:")
print(array_2d_copy / array_2d_new)

Копия двухмерного массива:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Новый двухмерный массив:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Сложение массивов:
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Вычитание массивов:
[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]

Умножение массивов (поэлементное):
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]

Деление массивов:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


### Задание 7: Объединение массивов с помощью concatenate

In [6]:
# Объединение по строкам (axis=0)
print("Объединение по строкам (axis=0):")
concat_axis0 = np.concatenate((array_2d_copy, array_2d_new), axis=0)
print(concat_axis0)
print(f"Размерность: {concat_axis0.shape}")
print()

# Объединение по столбцам (axis=1)
print("Объединение по столбцам (axis=1):")
concat_axis1 = np.concatenate((array_2d_copy, array_2d_new), axis=1)
print(concat_axis1)
print(f"Размерность: {concat_axis1.shape}")

Объединение по строкам (axis=0):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
Размерность: (6, 3)

Объединение по столбцам (axis=1):
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]
Размерность: (3, 6)


### Задание 8: Тригонометрические функции

In [7]:
# Создание массива случайных чисел
random_array = np.random.rand(5)
print("Массив случайных чисел:")
print(random_array)
print()

# Вычисление тригонометрических функций
print("Косинус:")
print(np.cos(random_array))
print()

print("Синус:")
print(np.sin(random_array))
print()

print("Тангенс:")
print(np.tan(random_array))

Массив случайных чисел:
[0.44142309 0.13766684 0.76947106 0.02532796 0.90686689]

Косинус:
[0.9041446  0.99053888 0.71827879 0.99967926 0.61621633]

Синус:
[0.42722658 0.13723241 0.69575541 0.02532525 0.78757694]

Тангенс:
[0.47252019 0.13854318 0.96864257 0.02533338 1.27808513]


### Задание 9: Применение булевых выражений

In [8]:
print("Массив случайных чисел:")
print(random_array)
print()

# Первое булево выражение: элементы больше 0.5
print("Булево выражение (элементы > 0.5):")
bool_expr1 = random_array > 0.5
print(bool_expr1)
print("Элементы больше 0.5:")
print(random_array[bool_expr1])
print()

# Второе булево выражение: элементы меньше или равны 0.3
print("Булево выражение (элементы <= 0.3):")
bool_expr2 = random_array <= 0.3
print(bool_expr2)
print("Элементы меньше или равны 0.3:")
print(random_array[bool_expr2])

Массив случайных чисел:
[0.44142309 0.13766684 0.76947106 0.02532796 0.90686689]

Булево выражение (элементы > 0.5):
[False False  True False  True]
Элементы больше 0.5:
[0.76947106 0.90686689]

Булево выражение (элементы <= 0.3):
[False  True False  True False]
Элементы меньше или равны 0.3:
[0.13766684 0.02532796]


### Задание 10: Эксперименты со срезами

In [9]:
# Создание массива для экспериментов со срезами
slice_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("Исходный массив:")
print(slice_array)
print()

# Первая строка
print("Первая строка (индекс 0):")
print(slice_array[0, :])
print()

# Первый столбец
print("Первый столбец (индекс 0):")
print(slice_array[:, 0])
print()

# Последняя строка
print("Последняя строка:")
print(slice_array[-1, :])
print()

# Последний столбец
print("Последний столбец:")
print(slice_array[:, -1])
print()

# Диапазон строк (строки с индексами 1 и 2)
print("Строки с индексами 1 и 2:")
print(slice_array[1:3, :])
print()

# Диапазон столбцов (столбцы с индексами 1 и 2)
print("Столбцы с индексами 1 и 2:")
print(slice_array[:, 1:3])
print()

# Комбинация срезов: строки 1-2, столбцы 2-3
print("Подмассив (строки 1-2, столбцы 2-3):")
print(slice_array[1:3, 2:4])
print()

# Каждая вторая строка
print("Каждая вторая строка:")
print(slice_array[::2, :])
print()

# Каждый второй элемент в каждой строке
print("Каждый второй элемент в каждой строке:")
print(slice_array[:, ::2])

Исходный массив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Первая строка (индекс 0):
[1 2 3 4]

Первый столбец (индекс 0):
[ 1  5  9 13]

Последняя строка:
[13 14 15 16]

Последний столбец:
[ 4  8 12 16]

Строки с индексами 1 и 2:
[[ 5  6  7  8]
 [ 9 10 11 12]]

Столбцы с индексами 1 и 2:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Подмассив (строки 1-2, столбцы 2-3):
[[ 7  8]
 [11 12]]

Каждая вторая строка:
[[ 1  2  3  4]
 [ 9 10 11 12]]

Каждый второй элемент в каждой строке:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
